import { screen, within } from '@testing-library/react'
import { afterEach, describe, expect, test, vi } from 'vitest'

import { jsonResponse, renderRoute } from '../../test/testUtils'
import { SiteAuditOverviewPage, SiteAuditSectionsPage } from './SiteAuditWorkspacePage'

let workspaceContext: {
  site: {
    id: number
    domain: string
    root_url: string
  }
  activeCrawlId: number | null
  baselineCrawlId: number | null
  updateCrawlContext: () => void
}

vi.mock('../sites/context', () => ({
  useSiteWorkspaceContext: () => workspaceContext,
}))

afterEach(() => {
  vi.restoreAllMocks()
})

const auditPayload = {
  crawl_job_id: 8,
  summary: {
    total_pages: 10,
    pages_missing_title: 1,
    pages_title_too_short: 0,
    pages_title_too_long: 0,
    pages_missing_meta_description: 1,
    pages_meta_description_too_short: 0,
    pages_meta_description_too_long: 0,
    pages_missing_h1: 1,
    pages_multiple_h1: 0,
    pages_missing_h2: 0,
    pages_missing_canonical: 1,
    pages_self_canonical: 0,
    pages_canonical_to_other_url: 0,
    pages_canonical_to_non_200: 0,
    pages_canonical_to_redirect: 0,
    pages_noindex_like: 0,
    pages_non_indexable_like: 0,
    pages_duplicate_title_groups: 1,
    pages_duplicate_meta_description_groups: 0,
    pages_thin_content: 1,
    pages_duplicate_content_groups: 0,
    pages_with_missing_alt_images: 1,
    pages_with_no_images: 0,
    oversized_pages: 0,
    js_heavy_like_pages: 1,
    rendered_pages: 1,
    pages_with_render_errors: 0,
    pages_with_schema: 1,
    pages_missing_schema: 9,
    pages_with_x_robots_tag: 0,
    pages_with_schema_types_summary: 1,
    broken_internal_links: 1,
    unresolved_internal_targets: 0,
    redirecting_internal_links: 0,
    internal_links_to_noindex_like_pages: 0,
    internal_links_to_canonicalized_pages: 0,
    redirect_chains_internal: 0,
  },
  pages_missing_title: [
    {
      page_id: 1,
      url: 'https://example.com/no-title',
      normalized_url: 'https://example.com/no-title',
      final_url: 'https://example.com/no-title',
      status_code: 200,
      title: null,
      title_length: null,
      meta_description: null,
      meta_description_length: null,
      h1: null,
      h1_length: null,
      h1_count: null,
      h2_count: null,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: false,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: true,
      meta_description_missing: true,
      h1_missing: true,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: true,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_title_too_short: [],
  pages_title_too_long: [],
  pages_missing_meta_description: [
    {
      page_id: 2,
      url: 'https://example.com/no-meta',
      normalized_url: 'https://example.com/no-meta',
      final_url: 'https://example.com/no-meta',
      status_code: 200,
      title: 'Meta missing',
      title_length: 12,
      meta_description: null,
      meta_description_length: null,
      h1: null,
      h1_length: null,
      h1_count: null,
      h2_count: null,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: false,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: true,
      h1_missing: false,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: true,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_meta_description_too_short: [],
  pages_meta_description_too_long: [],
  pages_missing_h1: [
    {
      page_id: 3,
      url: 'https://example.com/no-h1',
      normalized_url: 'https://example.com/no-h1',
      final_url: 'https://example.com/no-h1',
      status_code: 200,
      title: 'No H1',
      title_length: 5,
      meta_description: 'meta',
      meta_description_length: 4,
      h1: null,
      h1_length: null,
      h1_count: null,
      h2_count: null,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: false,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: false,
      h1_missing: true,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: true,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_multiple_h1: [],
  pages_missing_h2: [],
  pages_duplicate_title: [
    {
      value: 'Shared title',
      count: 2,
      pages: [
        { page_id: 11, url: 'https://example.com/a', normalized_url: 'https://example.com/a', status_code: 200, title: 'Shared title' },
        { page_id: 12, url: 'https://example.com/b', normalized_url: 'https://example.com/b', status_code: 200, title: 'Shared title' },
      ],
    },
  ],
  pages_duplicate_meta_description: [],
  pages_missing_canonical: [],
  pages_self_canonical: [],
  pages_canonical_to_other_url: [],
  pages_canonical_to_non_200: [],
  pages_canonical_to_redirect: [],
  pages_noindex_like: [],
  pages_non_indexable_like: [],
  broken_internal_links: [
    {
      link_id: 31,
      source_url: 'https://example.com/start',
      target_url: 'https://example.com/404',
      target_normalized_url: 'https://example.com/404',
      target_status_code: 404,
      final_url: 'https://example.com/404',
      redirect_hops: 1,
      target_canonical_url: null,
      target_noindex_like: false,
      target_non_indexable_like: false,
      signals: ['broken_internal'],
    },
  ],
  unresolved_internal_targets: [],
  redirecting_internal_links: [],
  internal_links_to_noindex_like_pages: [],
  internal_links_to_canonicalized_pages: [],
  redirect_chains_internal: [],
  pages_thin_content: [
    {
      page_id: 4,
      url: 'https://example.com/thin',
      normalized_url: 'https://example.com/thin',
      final_url: 'https://example.com/thin',
      status_code: 200,
      title: 'Thin content',
      title_length: 12,
      meta_description: 'meta',
      meta_description_length: 4,
      h1: 'H1',
      h1_length: 2,
      h1_count: 1,
      h2_count: 0,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: 50,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: false,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: false,
      h1_missing: false,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: false,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: true,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_duplicate_content: [],
  js_heavy_like_pages: [
    {
      page_id: 5,
      url: 'https://example.com/js',
      normalized_url: 'https://example.com/js',
      final_url: 'https://example.com/js',
      status_code: 200,
      title: 'JS page',
      title_length: 7,
      meta_description: 'meta',
      meta_description_length: 4,
      h1: 'H1',
      h1_length: 2,
      h1_count: 1,
      h2_count: 1,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: true,
      fetch_mode_used: null,
      js_heavy_like: true,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: false,
      h1_missing: false,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: false,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  rendered_pages: [
    {
      page_id: 6,
      url: 'https://example.com/rendered',
      normalized_url: 'https://example.com/rendered',
      final_url: 'https://example.com/rendered',
      status_code: 200,
      title: 'Rendered page',
      title_length: 13,
      meta_description: 'meta',
      meta_description_length: 4,
      h1: 'H1',
      h1_length: 2,
      h1_count: 1,
      h2_count: 1,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: true,
      render_attempted: true,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: false,
      h1_missing: false,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: false,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_with_render_errors: [],
  pages_with_schema: [
    {
      page_id: 7,
      url: 'https://example.com/schema',
      normalized_url: 'https://example.com/schema',
      final_url: 'https://example.com/schema',
      status_code: 200,
      title: 'Schema',
      title_length: 6,
      meta_description: 'meta',
      meta_description_length: 4,
      h1: 'H1',
      h1_length: 2,
      h1_count: 1,
      h2_count: 1,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: null,
      images_missing_alt_count: null,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: false,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: true,
      schema_count: 1,
      schema_types_json: ['Article'],
      schema_types_text: 'Article',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: false,
      h1_missing: false,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: false,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: false,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_missing_schema: [],
  pages_with_x_robots_tag: [],
  pages_with_schema_types_summary: [
    {
      value: 'Article',
      count: 1,
      pages: [
        { page_id: 7, url: 'https://example.com/schema', normalized_url: 'https://example.com/schema', status_code: 200, schema_types_json: ['Article'] },
      ],
    },
  ],
  pages_with_missing_alt_images: [
    {
      page_id: 8,
      url: 'https://example.com/image',
      normalized_url: 'https://example.com/image',
      final_url: 'https://example.com/image',
      status_code: 200,
      title: 'Image',
      title_length: 5,
      meta_description: 'meta',
      meta_description_length: 4,
      h1: 'H1',
      h1_length: 2,
      h1_count: 1,
      h2_count: 1,
      canonical_url: null,
      canonical_target_url: null,
      canonical_target_status_code: null,
      robots_meta: null,
      x_robots_tag: null,
      content_type: null,
      word_count: null,
      content_text_hash: null,
      images_count: 1,
      images_missing_alt_count: 1,
      html_size_bytes: null,
      was_rendered: false,
      render_attempted: false,
      fetch_mode_used: null,
      js_heavy_like: false,
      render_reason: null,
      render_error_message: null,
      schema_present: false,
      schema_count: null,
      schema_types_json: null,
      schema_types_text: '',
      page_type: 'other',
      page_bucket: 'other',
      page_type_confidence: 0,
      page_type_version: 'v1',
      page_type_rationale: null,
      has_render_error: false,
      has_x_robots_tag: false,
      response_time_ms: null,
      is_internal: true,
      depth: 1,
      fetched_at: null,
      error_message: null,
      title_missing: false,
      meta_description_missing: false,
      h1_missing: false,
      title_too_short: false,
      title_too_long: false,
      meta_description_too_short: false,
      meta_description_too_long: false,
      multiple_h1: false,
      missing_h2: false,
      canonical_missing: false,
      self_canonical: false,
      canonical_to_other_url: false,
      canonical_to_non_200: false,
      canonical_to_redirect: false,
      noindex_like: false,
      non_indexable_like: false,
      thin_content: false,
      duplicate_title: false,
      duplicate_meta_description: false,
      duplicate_content: false,
      missing_alt_images: true,
      no_images: false,
      oversized: false,
      clicks_28d: null,
      impressions_28d: null,
      ctr_28d: null,
      position_28d: null,
      gsc_fetched_at_28d: null,
      top_queries_count_28d: 0,
      has_gsc_28d: false,
      clicks_90d: null,
      impressions_90d: null,
      ctr_90d: null,
      position_90d: null,
      gsc_fetched_at_90d: null,
      top_queries_count_90d: 0,
      has_gsc_90d: false,
      priority_score: 0,
      priority_level: 'low',
      priority_rationale: '',
      traffic_component: 0,
      issue_component: 0,
      opportunity_component: 0,
      internal_linking_component: 0,
      opportunity_count: 0,
      primary_opportunity_type: null,
      opportunity_types: [],
      incoming_internal_links: 0,
      incoming_internal_linking_pages: 0,
      has_cannibalization: false,
      cannibalization_competing_urls_count: 0,
      cannibalization_overlap_strength: 0,
      cannibalization_strongest_competing_url: null,
      cannibalization_recommendation_type: null,
    },
  ],
  pages_with_no_images: [],
  oversized_pages: [],
}

function mockWorkspace(activeCrawlId: number | null, baselineCrawlId: number | null = 7) {
  workspaceContext = {
    site: {
      id: 5,
      domain: 'example.com',
      root_url: 'https://example.com',
    },
    activeCrawlId,
    baselineCrawlId,
    updateCrawlContext: () => undefined,
  }
}

describe('SiteAuditWorkspacePage', () => {
  test('renders overview with quick filters and resettable multi-select', async () => {
    mockWorkspace(8)
    vi.spyOn(globalThis, 'fetch').mockImplementation((input) => {
      if (String(input).includes('/crawl-jobs/8/audit')) {
        return jsonResponse(auditPayload)
      }
      throw new Error(`Unexpected request: ${String(input)}`)
    })

    const { user } = renderRoute(<SiteAuditOverviewPage />, {
      path: '/sites/:siteId/audit',
      route: '/sites/5/audit?active_crawl_id=8&baseline_crawl_id=7',
    })

    expect(await screen.findByRole('heading', { name: 'Audit' })).toBeInTheDocument()
    expect(screen.getByText('Audit groups')).toBeInTheDocument()
    expect(screen.getByText('Audit filters')).toBeInTheDocument()
    await user.click(screen.getByText('Operations'))
    expect(screen.getByRole('link', { name: 'Open Changes' })).toHaveAttribute(
      'href',
      '/sites/5/changes/audit?active_crawl_id=8&baseline_crawl_id=7',
    )
    expect(screen.getAllByRole('link', { name: 'Sections' })[0]).toHaveAttribute(
      'href',
      '/sites/5/audit/sections?active_crawl_id=8&baseline_crawl_id=7',
    )

    await user.click(screen.getByRole('button', { name: 'Pages' }))
    await user.click(screen.getByRole('button', { name: 'Links' }))

    expect(screen.getByText('Pages missing title')).toBeInTheDocument()
    expect(screen.getByText('Broken internal links')).toBeInTheDocument()
    expect(screen.queryByText('Pages with thin content')).not.toBeInTheDocument()

    const quickFiltersSection = screen.getByRole('heading', { name: 'Audit groups' }).closest('section')
    expect(quickFiltersSection).not.toBeNull()

    await user.click(within(quickFiltersSection as HTMLElement).getByRole('button', { name: 'Reset' }))

    expect(screen.getByText('Pages with thin content')).toBeInTheDocument()
  })

  test('renders expanded section details in sections mode', async () => {
    mockWorkspace(8)
    vi.spyOn(globalThis, 'fetch').mockImplementation((input) => {
      if (String(input).includes('/crawl-jobs/8/audit')) {
        return jsonResponse(auditPayload)
      }
      throw new Error(`Unexpected request: ${String(input)}`)
    })

    renderRoute(<SiteAuditSectionsPage />, {
      path: '/sites/:siteId/audit/sections',
      route: '/sites/5/audit/sections?active_crawl_id=8&baseline_crawl_id=7&page_size=12',
    })

    expect(await screen.findByRole('heading', { name: 'Audit Sections' })).toBeInTheDocument()
    expect(screen.getAllByRole('link', { name: 'Overview' })[0]).toHaveAttribute(
      'href',
      '/sites/5/audit?active_crawl_id=8&baseline_crawl_id=7',
    )
    expect(screen.getAllByText('https://example.com/no-title').length).toBeGreaterThan(0)
    expect(screen.getAllByText('https://example.com/start').length).toBeGreaterThan(0)
    expect(screen.getAllByText('https://example.com/schema').length).toBeGreaterThan(0)
  })

  test('shows an empty guidance state when no active crawl is selected', async () => {
    mockWorkspace(null, null)

    renderRoute(<SiteAuditOverviewPage />, {
      path: '/sites/:siteId/audit',
      route: '/sites/5/audit',
    })

    expect(await screen.findByText('Choose an active crawl to inspect the audit')).toBeInTheDocument()
  })
})
